# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_student_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Назва предмету')),
                ('data', models.DateTimeField(null=True, verbose_name='Дата і час ')),
                ('ticher_name', models.CharField(max_length=256, verbose_name='Викладач ')),
                ('exam_group', models.ManyToManyField(to='students.Group', verbose_name='Група')),
            ],
            options={
                'verbose_name_plural': 'Іспити',
                'verbose_name': 'Іспит',
            },
        ),
    ]
