# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_exam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='title',
            new_name='titles',
        ),
    ]
