# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20171001_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_exam',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.Group', verbose_name='Іспит'),
            preserve_default=False,
        ),
    ]
