# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20171002_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.Group', verbose_name='Іспит'),
        ),
    ]
