# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20171002_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exam',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_group',
            field=models.ManyToManyField(to='students.Group', verbose_name='Група'),
        ),
    ]
