# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_remove_exam_exam_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
