# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_auto_20171002_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exam_group',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.Group', verbose_name='Група'),
            preserve_default=False,
        ),
    ]
